### ISSUE TITLE
Strona "Oferta Biznesowa"

### ISSUE THREAD

**Issue by AdamWalkowski** [KlubJagiellonski/pola-web#181]
Dwa nagłówki.
Pierwszy. Znak towarowy. Skopowiane z:
https://klubjagiellonski.pl/projekty/oferta-biznesowa-centrum-analiz-klubu-jagiellonskiego/

Drugi. Pola w sklepie internetowym. Treść:
https://docs.google.com/document/d/1Bd4YKlLJyOGOxg7KqYVgTiwjuDMwx5QtfPi88O2sJcA/edit

"mniejsze grafiki. Pierwsza grafika mogłaby być po prawej, a tekst równolegle po lewej. Tak jak na stronie "O Poli"."

**Comment by MatPerowicz** [comment]
@AdamWalkowski będę przygotowywał treść tej zakładki, będzie niestety dość obszerna
