### ISSUE TITLE
Ikonka "i" po lewej stronie wyszukiwarki

### ISSUE THREAD

**Issue by AdamWalkowski** [KlubJagiellonski/pola-web#197]
Użytkownik musi wiedzieć jakie funkcje ma wyszukiwarka. Dlatego proponuję umieścić ikonkę "i" na lewo od pola tekstowego. To chyba najprostszy sposób żeby dać znać ludziom co mogą wpisać w polu tekstowym? Zawsze będzie można łatwo to edytować.

![image](https://user-images.githubusercontent.com/52166969/135463227-f3aeec99-25b8-44c5-96ed-99f32f665576.png)

**Comment by MatPerowicz** [comment]
Tekst pod ikonką "I": Jeśli chcesz znaleźć produkty polskich firm, możesz wkleić lub wpisać w polu tekstowym kod EAN dowolnego produktu. Kod znajdziesz na opakowaniu lub w opisie produktu na stronie sklepu internetowego.

Możesz także wpisać nazwę producenta lub nazwę produktu. Jeśli potrzebujesz więcej informacji lub chcesz zgłosić błąd, prosimy o kontakt: pola@klubjagiellonski.pl

**Comment by MatPerowicz** [comment]
@AdamWalkowski zamówiłem nową ikonkę "i", będzie we wtorek
