### ISSUE TITLE
Hiperłącza na stronie głównej

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-web#265]
Przekierowania do właściwych stron w kilku różnych miejscach (np. zbiórka, media społecznościowe, formularz dodaj firmę)

**Comment by AdamWalkowski** [comment]
Uzupełnione przekierowania na podstawie dokumentu:
https://docs.google.com/document/d/1qJjkaOXgxXJKjMVzdf4qn4TWMdFF0zL1AJibjQtjiSU

HOME
1. Przekierowanie do strony zbiórki tutaj. link do zbiórki: https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/ 
2. Przekierowanie do strony “o Poli” https://klubjagiellonski.github.io/pola-web/about 
3. Przekierowanie do strony: https://klubjagiellonski.github.io/pola-web/friends
4. Przekierowanie do zakładki “Dołącz do zespołu” https://klubjagiellonski.github.io/pola-web/join 
5. Przekierowanie nawigacji “ Wesprzyj aplikację” na stronę zbiórki: https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/ 

![image](https://user-images.githubusercontent.com/4296655/140043771-1355be7f-547f-4404-9d5a-bd243671c758.png)
