### ISSUE TITLE
Oferta biznesowa - sekcja "Rozszerzony profil firmy"

### ISSUE THREAD

**Issue by AdamWalkowski** [KlubJagiellonski/pola-web#313]
Dokument z treścią:
https://docs.google.com/document/d/1ADhxymZDtk8lpJemFMJhXXagMKS2mOfJ7OmH04bjfmQ/edit

**Comment by MatPerowicz** [comment]
Czy jest możliwość stworzenia takiej opcji? Najlepiej, aby z poziomu CMS dało się dodawać logotypy, link itp. Połączone z tym issues https://github.com/KlubJagiellonski/pola-web/issues/374

@AdamWalkowski @mik-laj
