### ISSUE TITLE
Funkcjonalność wyszukiwarki

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-web#32]
Szanowni,

Potrzebujemy zbudować trochę zarówno strony, jak i komponenty, które pozwolą nam na zbudowanie wyszkiwarki. Wyszkiwarka będzie wykorzystywać API dostarczane przez pola-backend: https://github.com/KlubJagiellonski/pola-backend/issues/189

Pomocne będzie tutaj pewnie doświadczenie z wyszukiwarką, która już wcześniej zbudowaliśmy dla pola-app.pl

**Comment by MatPerowicz** [comment]
@AdamWalkowski tutaj dajmy po prostu mail: pola@klubjagiellonski.pl zamiast przycisku, aby nie utrudniać użytkownikom kontaktu.

![Przechwytywanie](https://user-images.githubusercontent.com/52166969/139654824-4f9a3b02-f19c-48d1-8866-6e0a50fb1dab.PNG)
lkowski

**Comment by MatPerowicz** [comment]
@AdamWalkowski tutaj dajmy napis „Skanuj kody w aplikacji:” i Przyciski do pobrania z konkretnych sklepów, te, które są na stronie głównej.

![image](https://user-images.githubusercontent.com/52166969/140741564-e003d7ed-8674-412f-b60e-bf23c4159ca7.png)
![image](https://user-images.githubusercontent.com/52166969/140742528-9ed122d0-ff53-45a3-a0d9-59d20e8c2bad.png)

**Comment by MatPerowicz** [comment]
@mik-laj prośba aby zadbać by to się nie wyświetlało. 
![image](https://user-images.githubusercontent.com/52166969/140917731-5be34d90-fb86-4a87-b80c-4ba701b8756a.png)
