### ISSUE TITLE
Pasek zakładek przysłania suwak z prawej strony

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-web#339]
Po wpisaniu tekstu w wyszukiwarce, gdy chce się przewinąć w dół, nie widać suwaka po prawej stronie.

![image](https://user-images.githubusercontent.com/52166969/141067059-dcc3878b-16b6-4f5f-ae85-7af8bb6eaafb.png)

**Comment by AdamWalkowski** [comment]
A nie jest właśnie ładniej, jak jest przesłonięty?
