### ISSUE TITLE
Niepełna stopka w widoku mobilnym

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-web#341]
Brakuje przede wszystkim "Polityki Prywatności" na mobilu nie da się do niej trafić.

![image](https://user-images.githubusercontent.com/52166969/141068102-93617d48-2532-4c6a-a8eb-615fb93b17b8.png)

**Comment by AdamWalkowski** [comment]
Polityka prywatności oraz uzupełnienie danych o firmie były cały czas umyślnie wyłączone dla mobile. @zyzik1248 Wiesz dlaczego?
