### ISSUE TITLE
Komponent datków

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-web#37]
Szanowni,

Chcemy zbudować komponent datków.

Pozdrawiam

**Comment by mik-laj** [comment]
@MatPerowicz Czy możesz powiedzieć coś o tym komponencie więcej? Jakbyś chciał, aby on działał?

**Comment by MatPerowicz** [comment]
Do usunięcia, ponieważ mamy już to https://github.com/KlubJagiellonski/pola-web/issues/195
