### ISSUE TITLE
Strona "O Poli" i "Przyjaciele"

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-web#40]
Chcemy wyświettlić informacje o poili, jej filozofii działania  oraz algorytmie,

1. Usunąć partnerów żeby nie byli w dwóch miejscach.
2. Podmienić grafikę soku na taką bez logotypu Poli.
3. Na stronie Przyjaciół Poli można też dać grafikę bez logotypu Poli.

**Comment by MatPerowicz** [comment]
@AdamWalkowski z tej strony trzeba usunąć partnerów, aby nie byli w dwóch miejscach

**Comment by MatPerowicz** [comment]
@zyzik1248 @AdamWalkowski prośba o podmianę grafiki na tej stronie na tą 
![2-bez_loga](https://user-images.githubusercontent.com/52166969/140030192-44dd9cd9-4133-4a8d-98d2-86680016d03f.png)

**Comment by AdamWalkowski** [comment]
@MatPerowicz Ten obrazek powoduje błąd i strona się sypie. Możesz znaleźć inną wersję i przesłać plik np mailem?
