### ISSUE TITLE
Bojkot rosyjskich produktów

### ISSUE THREAD

**Issue by AdamWalkowski** [KlubJagiellonski/pola-web#464]
W zaistniałej sytuacji należałoby stworzyć narzędzia pozwalające sprawdzić, które produkty są rosyjskie i białoruskie.

W tym celu:

po zeskanowaniu kodów zaczynających się na 460-469 (Rosja) oraz 481 (Białoruś), dać komunikat „Ten produkt pochodzi z kraju, który dokonał inwazji na Ukrainę. Zastanów się, czy chcesz go kupić”

![image-rosja](https://user-images.githubusercontent.com/4296655/156718574-eb115acc-dd17-4c2a-9ec7-2bdeb97bbaa1.png)

![Screenshot_20220303_175205_pl pola_app](https://user-images.githubusercontent.com/4296655/156718496-aa3d4482-4389-4bc1-9b77-f790aa2b17eb.jpg)

**Comment by mik-laj** [comment]
To już jest zrobione. API zwraca ten komunikat.
