### ISSUE TITLE
Strona przyjaciele poli

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-web#52]
Szanowni,

Potrzebujemy strony, która zawiera podstawowe informacje o bieżących przyjaciela Poli oraz zachęci do dołączenia nowych, W tym celu potrzebujemy komponentów: partnerzy https://github.com/KlubJagiellonski/pola-web/issues/38, infografika https://github.com/KlubJagiellonski/pola-web/issues/39

Źródło danych przyjaciół to plik YAML.

Z wyrazami szacunku,
Kamil Breguła

**Comment by MatPerowicz** [comment]
@AdamWalkowski @zyzik1248 chyba lepiej wstawić grafikę bez tego znaczka Poli, załączam

![3_bez_tła](https://user-images.githubusercontent.com/52166969/140033369-df754541-4f7d-45a8-932f-b57897466e8c.png)
