### ISSUE TITLE
Strona "Zespół"

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-web#55]
Szanowni,

Chcemy wyświetlić informacje o osobach, które budują tą strone,
https://docs.google.com/document/d/111y5Z3RiPXiEB4t18kau_tkUZvvw6ZUhQTT4XYcNRH4/edit

Z wyrazami szacunku,
Kamil Breguła

**Comment by MatPerowicz** [comment]
@AdamWalkowski przygotuję niebawem treść tej zakładki

**Comment by AdamWalkowski** [comment]
Moim zdaniem widok dwukolumnowy nie wygląda tutaj dobrze
