### ISSUE TITLE
Podwójne pliki Przyjaciół Poli

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-web#815]
Obecnie informacje o przyjaciołach Poli trzeba zmieniać w dwóch miejscach:

Informacje, które wyświetlają się w menu aplikacji są na backendzie:
https://github.com/KlubJagiellonski/pola-backend/blob/99182940076d65821942ee6fe0752235aab21485/pola/templates/partiales/friends.html#L4

Informacje, które wyświetlają się na stronie i na webview są na pola-web:
https://github.com/KlubJagiellonski/pola-web/blob/87b4f77591b8594ed885a72271857ab1b1dae3d8/webviews/friends/index.html#L36

Czy możemy to ujednolicić, aby wszelkie zmiany były robione tylko raz?

**Comment by AdamWalkowski** [comment]
Można np stworzyć API zwracające listę wszystkich aktualnych Przyjaciół Poli wraz ze wszystkimi informacjami szczegółowymi. Takie API zwracałoby dokładnie zawartość pliku friends.html z Pola Backend. Natomiast lepiej, aby format tego pliku był wówczas JSON, a nie HTML

**Comment by AdamWalkowski** [comment]
aby issue było widoczne na tablicy projektu, potrzeba zaznaczyć opcje po prawej stronie
![image](https://github.com/KlubJagiellonski/pola-web/assets/4296655/bae747f1-0c86-4868-a8a8-cc2f9baca2ad)

**Comment by MatPerowicz** [comment]
@zyzik1248 już rozwiązała problem :)
